#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

echo "🚀 Starting Deployment Configuration..."

echo "============================================================"
echo " FIREBASE APP HOSTING (Next.js Fullstack)"
echo "============================================================"
echo "Note: Firebase App Hosting natively supports Next.js."
echo "It automatically builds and deploys your Next.js app (including Server Actions and API routes) to Google Cloud."
echo ""
echo "Steps to deploy:"
echo "1. Push your code to a GitHub repository."
echo "2. Go to the Firebase Console: https://console.firebase.google.com/"
echo "3. Select your project -> Build -> App Hosting."
echo "4. Click 'Get started' and connect your GitHub repository."
echo "5. Configure your build settings (root directory, branch)."
echo "6. Click 'Deploy'."
echo ""
echo "Firebase App Hosting will automatically detect your Next.js app, install dependencies, build it, and deploy both the static assets and the serverless functions required for your API routes (like the SSE endpoint) and Server Actions."
echo ""
echo "✅ Firebase App Hosting is ready."
echo "============================================================"
echo " SUPABASE (Database Setup)"
echo "============================================================"
echo "1. Go to https://supabase.com/ and create a new project."
echo "2. Once your database is ready, go to the SQL Editor."
echo "3. Copy the contents of migrations.sql and run it to create the 'jobs' table."
echo "4. Go to Project Settings -> API."
echo "5. Copy the Project URL and the anon/public key."
echo ""
echo "============================================================"
echo " ENVIRONMENT VARIABLES (Firebase App Hosting)"
echo "============================================================"
echo "To securely add your Supabase credentials to Firebase App Hosting:"
echo "1. Go to your Firebase Console -> App Hosting -> [Your Backend] -> Settings -> Environment Variables (or Secrets)."
echo "2. Add the following environment variables:"
echo "   - NEXT_PUBLIC_SUPABASE_URL = <your_supabase_project_url>"
echo "   - NEXT_PUBLIC_SUPABASE_ANON_KEY = <your_supabase_anon_key>"
echo "3. Trigger a new rollout/deployment for the environment variables to take effect."
echo "============================================================"
echo "🎉 Firebase App Hosting and Supabase are ready to go."

