#!/usr/bin/env bash

# find src/utils -type f ! -name "*.test.ts" | sed 's|src/utils/||; s|\.ts$||' | sort

FILES=(
# "array_match"
"array"
"assertEqArrays"
"asserts"
# "async"
# "char"
# "char-uppercase-cyrillic"
# "char-uppercase-latin"
# "confirmStable"
# "db-utils"
# "deepEqual"
"delay"
# "dictionary"
# "dict-parser"
"dom"
# "downloadAsTextFile"
# "duplicate-report-streamer"
# "english-khmer-en-kh-cache-db"
# "english-khmer-en-kh-extractor"
# "english-khmer-en-kh-fetch"
# "english-khmer-kh-en-cache-db"
# "english-khmer-kh-en-extractor"
# "english-khmer-kh-en-fetch"
# "entries"
# "enum"
# "generate-khmer-segments-to-ru-transliteration-automatic"
# "get-new-words-to-fetch"
# "google-translate-puppeteer"
# "google-translate"
# "html-text-parser"
# "iterator"
# "khmer-colorize-html"
# "khmer-consonants-vovels-groups"
# "khmer-consonants-vovels"
# "khmerHasSimilarPronounciationTo"
# "khmer_parse_tokenize"
# "khmer_parse_tokenize_with_series"
# "khmer_segmentation"
# "khmer-table-grid-data"
# "khmerToRussianOutput"
# "khmerToRussian"
# "khmer-word-dictionary-index"
# "khmer-word"
# "lazy"
# "LoadingOrErrorOrSuccess"
# "log"
# "map-get-set-using-normalizer"
"map"
# "memoize-async"
# "memoize"
# "nil"
# "n-of-days"
"non-empty-array"
"non-empty-array-valibot"
# "non-empty-array-zod"
"non-empty-map"
"non-empty-map-valibot"
# "non-empty-map-zod"
"non-empty-record"
"non-empty-record-valibot"
"non-empty-set"
"non-empty-set-valibot"
# "non-empty-set-zod"
"non-empty-string-trimmed"
"non-empty-string-trimmed-valibot"
# "non-empty-string-trimmed-zod"
"non-empty-string"
"non-empty-string-valibot"
# "non-empty-string-zod"
"non-khmer-word"
# "non-khmer-word-zod"
# "normalizeKhmerDiactricsInsensitive"
"number/countDigitsBeforeAndAfterDot"
"number/nOfDigitsAfterDot"
"number/nOfDigitsBeforeDot"
# "open-google-translate-cached"
# "open-google-translate-cache"
# "page"
# "parseRussianLine"
# "pluralize"
# "pojo"
"record"
# "replaceHtmlTextNodesWithMaybeOtherHtml"
# "report-streamer"
# "repro_error"
# "retry"
# "run-fetch-cycle"
# "russianToKhmerRegex"
# "russian-word-dictionary-index"
# "russian-word"
# "selectOption"
# "setOfKhmerWords"
# "sets-get-set-using-normalizer"
"sets"
# "slugifyKhmer"
"sort"
# "string-contains-khmer-char"
# "string-cyrillic-phrase"
# "string-lowercase-cyrillic"
# "string-lowercase-latin"
# "string-only-khmer-and-without-html"
# "string-only-khmer"
# "stringToUid"
# "string"
# "string-without-khmer-and-html"
# "string-without-khmer"
# "strip-html"
# "these-named"
# "these"
"toBoolean"
# "toHex"
"toNumber/test-data"
"toNumber/validInt-valibot.test"
"toNumber/validInt-valibot"
"toNumber/validInt.test"
"toNumber/validInt"
"toNumber/validNonNegativeInt-valibot.test"
"toNumber/validNonNegativeInt-valibot"
"toNumber/validNonNegativeInt.test"
"toNumber/validNonNegativeInt"
"toNumber/validNonNegativeNumber-valibot.test"
"toNumber/validNonNegativeNumber-valibot"
"toNumber/validNonNegativeNumber.test"
"toNumber/validNonNegativeNumber"
"toNumber/validNumber-valibot.test"
"toNumber/validNumber-valibot"
"toNumber/validNumber.test"
"toNumber/validNumber"
"toNumber/validPercent-valibot.test"
"toNumber/validPercent-valibot"
"toNumber/validPercent.test"
"toNumber/validPercent"
"toValidDate"
# "translate-dict"
"types"
"undefined"
# "uuid"
# "validateMarkdownLine"
# "wiktionary-cache-db"
# "wiktionary-cache"
# "wiktionary-cleaner"
# "wiktionary-extractor2"
# "wiktionary-extractor"
# "wiktionary-fetch"
# "wiktionary-parse"
# "wiktionary-short-description-km-extractor"
# "wiktionary-short-description-ru-extractor"
# "withError"
# "zipStrictObjects"
)

SRC_BASE="$HOME/projects/khmer/gemini-ocr-automate-images-upload-chrome-extension/src/utils"
DST_BASE="src/utils"

for FILE in "${FILES[@]}"; do
  # Ensure the destination directory exists
  SRC_PATH="$SRC_BASE/$FILE.ts"
  DST_PATH="$DST_BASE/$FILE.ts"
  DST_DIR=$(dirname "$DST_PATH")
  mkdir -p "$DST_DIR"

  # Create the symlink
  # ln -sf "$SRC_PATH" "$DST_PATH"
  rm -f "$DST_PATH" && cp -f "$SRC_PATH" "$DST_PATH"
done
